### ISSUE TITLE
Gitlab CI hangs on publish

### ISSUE THREAD

**Issue by Jdruwe** [expo/expo-cli#203]
I have an issue in my Gitlab CI setup. Here is my .gitlab-ci.yml file:

```
image: jdruwe/alpine-node-git:latest

variables:
  DOCKER_DRIVER: overlay

stages:
  - publish

publish-develop:
  stage: publish
  script:
  - npm install
  - npm i -g exp
  - exp login -u $EXPO_USERNAME -p $EXPO_PASSWORD
  - exp publish --release-channel develop
```

The 'exp login' command works fine but it seems to hang on the publish command, this is what I keep seeing (it never proceeds):

<img width="937" alt="screen shot 2018-04-28 at 22 22 44" src="https://user-images.githubusercontent.com/4804496/39400549-b5f6af14-4b32-11e8-99c9-eb0fd6ca6080.png">

I've no idea why this is happening, there is also no logging for me to look into it seems. Any help would be appreciated!

NOTE: I also get the warning on my local machine but the publish does start afterwards with `Starting Metro Bundler on port 19001.` ...
