### ISSUE TITLE
Handle ENOSPC error (fs.inotify.max_user_watches reached)

### ISSUE THREAD

**Issue by fson** [expo/expo-cli#277]
Expo CLI should catch the `ENOSPC` error (https://github.com/expo/expo/issues/2944) from exceeding the `inotify` limits on Linux and suggest a fix to the user (increase the `fs.inotify.max_user_watches` setting).

The corresponding error in Watchman: https://github.com/facebook/watchman/blob/02d1d89b093bdbacdaa5e37471cef00080954ac5/error_category.cpp#L30-L41

**Comment by fson** [comment]
Unfortunately the best we can do is suggest increasing the amount of watches. Expo CLI can't automatically do this, because changing the setting requires superuser privileges.

You only need to configure the setting once per server, it can be done by running this command:
```
echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
echo fs.inotify.max_queued_events=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

**Comment by smithmr** [comment]
We are using GitLab CI/CD When we run `expo publish --non-interactive --release-channel develop` We get the same error 
`[06:27:32] Building iOS bundle
[06:27:42] fs.js:1384
[06:27:42]     throw error;
[06:27:42]     ^
[06:27:42] 
[06:27:42] Error: watch /builds/divdot/mobile-app/node_modules/react-native/ReactAndroid/src/main/libraries/fbcore/src/test/java/com/facebook/powermock ENOSPC
[06:27:42]     at FSWatcher.start (fs.js:1382:19)
[06:27:42]     at Object.fs.watch (fs.js:1408:11)
[06:27:42]     at NodeWatcher.watchdir (/builds/divdot/mobile-app/node_modules/sane/src/node_watcher.js:175:20)
[06:27:42]     at Walker.<anonymous> (/builds/divdot/mobile-app/node_modules/sane/src/common.js:116:12)
[06:27:42]     at emitTwo (events.js:126:13)
[06:27:42]     at Walker.emit (events.js:214:7)
[06:27:42]     at /builds/divdot/mobile-app/node_modules/walker/lib/walker.js:69:16
[06:27:42]     at go$readdir$cb (/builds/divdot/mobile-app/node_modules/graceful-fs/graceful-fs.js:162:14)
[06:27:42]     at FSReqWrap.oncomplete (fs.js:135:15)
[06:27:42] socket hang up
[06:27:42] Set EXPO_DEBUG=true in your env to view the stack trace.`

**Comment by smithmr** [comment]
## FIXED
I added @fson commands to my .gitlab-ci.yml file
`before_script:
- echo fs.inotify.max_user_instances=524288 | tee -a /etc/sysctl.conf && sysctl -p
- echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sysctl -p
- echo fs.inotify.max_queued_events=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

**Comment by byCedric** [comment]
This is an interesting one, I've been trying to get an implementation out for GitHub Actions and Expo but I ran into this one too. Have mailed the GitHub team trying to get it resolved, they made a case but couldn't tell when they will look at it. Unfortunately, changing the inotify limit yourself is not allowed on GitHub Actions. You may encounter `changing ... on a read-only system` message too.

The most interesting part is that I could use `expo publish` without issues on quite some CI vendors. I listed them below with their inotify limits. I also ruled out some other possible complications related to running out of disk space or insufficient internal memory.

vendor              | fs.inotify.max_user_watches | works?
---                 | ---                         | ---
Bitbucket Pipelines | `524288`                    | **yes**
Circle CI           | `524288`                    | **yes**
Drone IO            | `8192`                      | **yes**
GitHub Actions      | `8192`                      | _no_
Travis CI           | `8192`                      | _did not finish in time_

**Comment by smithmr** [comment]
> This is an interesting one, I've been trying to get an implementation out for GitHub Actions and Expo but I ran into this one too. Have mailed the GitHub team trying to get it resolved, they made a case but couldn't tell when they will look at it. Unfortunately, changing the inotify limit yourself is not allowed on GitHub Actions. You may encounter `changing ... on a read-only system` message too.
> 
> The most interesting part is that I could use `expo publish` without issues on quite some CI vendors. I listed them below with their inotify limits. I also ruled out some other possible complications related to running out of disk space or insufficient internal memory.
> 
> vendor	fs.inotify.max_user_watches	works?
> [Bitbucket Pipelines](https://bitbucket.org/product/features/pipelines)	`524288`	**yes**
> [Circle CI](https://circleci.com/)	`524288`	**yes**
> [Drone IO](https://drone.io)	`8192`	**yes**
> [GitHub Actions](https://github.com/features/actions)	`8192`	_no_
> [Travis CI](https://travis-ci.org/)	`8192`	_did not finish in time_

GitLab CI works too :)

**Comment by bduff9** [comment]
I am unsure what has changed but bitbucket pipelines started failing for me tonight in a production project that is over a year old.  I cannot use the workaround since I get the read-only system message.  Would appreciate any suggestions as we currently cannot use our pipeline.

**Comment by antila** [comment]
> 
> 
> I am unsure what has changed but bitbucket pipelines started failing for me tonight in a production project that is over a year old. I cannot use the workaround since I get the read-only system message. Would appreciate any suggestions as we currently cannot use our pipeline.

The exact same thing happened to us. If  you run `- sysctl fs.inotify.max_user_watches` as a step in the pipeline it shows that there's only 8192 available watchers. I think it's a regression on their side. https://bitbucket.org/site/master/issues/15165/increase-fsinotifymax_user_watches

**Comment by IgorRamosBR** [comment]
> ## FIXED
> I added @fson commands to my .gitlab-ci.yml file
> `before_script:`
> `- echo fs.inotify.max_user_instances=524288 | tee -a /etc/sysctl.conf && sysctl -p`
> `- echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sysctl -p`
> `- echo fs.inotify.max_queued_events=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

Hi @smithmr, what is image you are using in your .gitlab-ci.yml file? Could I adapt theses scripts to an Alpine image?

**Comment by smithmr** [comment]
@IgorRamosBR I am using Expo to build our app

**Comment by IgorRamosBR** [comment]
> @IgorRamosBR I am using Expo to build our app

@smithmr Ok, but you said that added thoses scripts in .gitlab-ci.yml and worked. I was trying to do the same, but I couldn't. 

Therefore I would like to know what image you are using in .gitlab-ci.yml.

**Comment by smithmr** [comment]
@IgorRamosBR DOCKER, sorry misunderstood.

**Comment by IgorRamosBR** [comment]
@smithmr Ok, docker. But, I used node:8 image and node:alpine and I couldn't set the scripts in theses images. I would like to know one simple example of .gitlab-cy.yml with theses scripts. 

Do you could provide me this example? It would help me a lot...

**Comment by smithmr** [comment]
> @smithmr Ok, docker. But, I used node:8 image and node:alpine and I couldn't set the scripts in theses images. I would like to know one simple example of .gitlab-cy.yml with theses scripts.
> 
> Do you could provide me this example? It would help me a lot...

```yaml
image: node:8

stages:
  - build

package-develop:
  type: build
  only:
    - develop
  environment:
    name: development/package
    url: https://gitlab.com/divdot/mobile-app/-/jobs/artifacts/develop/browse/binaries?job=package-develop
  before_script:
    - echo "$NPMRC" > ~/.npmrc
    - echo "$JS_CONFIG_ENV" > ./configEnv.js
    - echo fs.inotify.max_user_instances=524288 | tee -a /etc/sysctl.conf && sysctl -p
    - echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p
    - echo fs.inotify.max_queued_events=524288 | tee -a /etc/sysctl.conf && sysctl -p
    - npm config get registry
    - npm install -g expo-cli
    - mkdir binaries
    - expo login -u ${EXPO_USERNAME} -p ${EXPO_PASSWORD}
  script:
    - npm install
    - expo publish --non-interactive --release-channel develop
    - expo build:android --non-interactive --no-publish --no-wait --release-channel develop
    - ./ci_scripts/wait.sh android
    - curl -o binaries/divdot-develop-${CI_COMMIT_SHA}.apk "$(expo url:apk --non-interactive)"
    - expo build:ios --non-interactive --no-publish --no-wait --release-channel develop
    - ./ci_scripts/wait.sh ios
    - curl -o binaries/divdot-develop-${CI_COMMIT_SHA}.ipa "$(expo url:ipa --non-interactive)"
  artifacts:
    name: 'mobile-develop-${CI_COMMIT_SHA}'
    when: on_success
    paths:
      - binaries

package-production:
  type: build
  only:
    - master
  environment:
    name: production/package
    url: https://gitlab.com/divdot/mobile-app/-/jobs/artifacts/master/browse/binaries?job=package-production
  before_script:
    - echo "$NPMRC" > ~/.npmrc
    - echo "$JS_CONFIG_ENV" > ./configEnv.js
    - npm config get registry
    - npm install -g expo-cli
    - mkdir binaries
    - expo login -u ${EXPO_USERNAME} -p ${EXPO_PASSWORD}
  script:
    - npm install
    - expo publish --non-interactive --release-channel production
    - expo build:android --non-interactive --no-publish --no-wait --release-channel production
    - ./ci_scripts/wait.sh android
    - curl -o binaries/divdot-production-${CI_COMMIT_SHA}.apk "$(expo url:apk --non-interactive)"
    - expo build:ios --non-interactive --no-publish --no-wait --release-channel production
    - ./ci_scripts/wait.sh ios
    - curl -o binaries/divdot-production-${CI_COMMIT_SHA}.ipa "$(expo url:ipa --non-interactive)"
  artifacts:
    name: 'mobile-production-${CI_COMMIT_SHA}'
    when: on_success
    paths:
      - binaries
```

**Comment by stanvit** [comment]
@anton-bot , AWS Codebuild allows to modify `fs.inotify.max_user_watches` if privileged mode is enabled for your builds:

```
[Container] 2019/07/11 06:18:34 Running command sysctl fs.inotify.max_user_watches 
fs.inotify.max_user_watches = 8192 
 
[Container] 2019/07/11 06:18:34 Running command sysctl fs.inotify.max_user_watches=524288 
fs.inotify.max_user_watches = 524288 
 
[Container] 2019/07/11 06:18:34 Running command sysctl fs.inotify.max_user_watches 
fs.inotify.max_user_watches = 524288 
```

**Comment by slorber** [comment]
@smithmr just curious how you implemented `./ci_scripts/wait.sh` and why use --no-wait? Also why not building ios and android at the same time?

**Comment by slorber** [comment]
@smithmr Also want to add that there's a missing "sudo" in your code snippet I think that's why people have errors `Read-only file system`. You should rather edit them and add the missing sudo so that people can just copy paste your snippet ;)

**Comment by slorber** [comment]
Actually, it seems it's impossible to modify the inotify limits inside docker, unless this container is running in "privileged mode".

Even the following, supposed to only update the limit temporarily, does not work:

```
sudo sysctl fs.inotify.max_user_instances=524288
sudo sysctl fs.inotify.max_user_watches=524288
sudo sysctl fs.inotify.max_queued_events=524288
```

According to gitlab doc there's a way to execute in privileged mode:

```
[[runners]]
  executor = "docker"
  [runners.docker]
    privileged = true
```

I have no idea if this is a good idea to do so (what do you think?)


Also it seems it's possible to set sysctl via docker. 

Gitlab Runner offers a way to configure it (I guess other CI systems might have something similar):

```
[runners.docker.sysctls]
    "fs.inotify.max_user_instances" = "524288"
    "fs.inotify.max_user_watches" = "524288"
    "fs.inotify.max_queued_events" = "524288"
```

Didn't try yet as I'm not CI admin

**Comment by smithmr** [comment]
> Actually, it seems it's impossible to modify the inotify limits inside docker, unless this container is running in "privileged mode".
> 
> Even the following, supposed to only update the limit temporarily, does not work:
> 
> ```
> sudo sysctl fs.inotify.max_user_instances=524288
> sudo sysctl fs.inotify.max_user_watches=524288
> sudo sysctl fs.inotify.max_queued_events=524288
> ```
> 
> According to gitlab doc there's a way to execute in privileged mode:
> 
> ```
> [[runners]]
>   executor = "docker"
>   [runners.docker]
>     privileged = true
> ```
> 
> I have no idea if this is a good idea to do so (what do you think?)
> 
> Also it seems it's possible to set sysctl via docker.
> 
> Gitlab Runner offers a way to configure it (I guess other CI systems might have something similar):
> 
> ```
> [runners.docker.sysctls]
>     "fs.inotify.max_user_instances" = "524288"
>     "fs.inotify.max_user_watches" = "524288"
>     "fs.inotify.max_queued_events" = "524288"
> ```
> 
> Didn't try yet as I'm not CI admin



> @smithmr just curious how you implemented `./ci_scripts/wait.sh` and why use --no-wait? Also why not building ios and android at the same time?

The IOS build does not wait for Android build. 

Something to note is that we were using a private runner on GCP and not the Gitlab runner.

**Comment by idudinov** [comment]
just asking: is this issue about watching file changes? if so, is it possible to work around this by disabling watching in Metro config during builds?

**Comment by neutrous** [comment]
> > Actually, it seems it's impossible to modify the inotify limits inside docker, unless this container is running in "privileged mode".
> > Even the following, supposed to only update the limit temporarily, does not work:
> > ```
> > sudo sysctl fs.inotify.max_user_instances=524288
> > sudo sysctl fs.inotify.max_user_watches=524288
> > sudo sysctl fs.inotify.max_queued_events=524288
> > ```
> > 
> > 
> > According to gitlab doc there's a way to execute in privileged mode:
> > ```
> > [[runners]]
> >   executor = "docker"
> >   [runners.docker]
> >     privileged = true
> > ```
> > 
> > 
> > I have no idea if this is a good idea to do so (what do you think?)
> > Also it seems it's possible to set sysctl via docker.
> > Gitlab Runner offers a way to configure it (I guess other CI systems might have something similar):
> > ```
> > [runners.docker.sysctls]
> >     "fs.inotify.max_user_instances" = "524288"
> >     "fs.inotify.max_user_watches" = "524288"
> >     "fs.inotify.max_queued_events" = "524288"
> > ```
> > 
> > 
> > Didn't try yet as I'm not CI admin
> 
> > @smithmr just curious how you implemented `./ci_scripts/wait.sh` and why use --no-wait? Also why not building ios and android at the same time?
> 
> The IOS build does not wait for Android build.
> 
> Something to note is that we were using a private runner on GCP and not the Gitlab runner.

This seems not working. Docker only support parts of the namespaces as described [here](https://docs.docker.com/engine/reference/commandline/run/).

Actually, you just need to execute the following commands on the docker's host machine:

```
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

The dockers inlcuding gitlab runner would automatically inherit the host's configurations from `/proc`

**Comment by hashim-sohail** [comment]
Getting the same error in my custom docker image that is being used in GitHub Actions. Can't modify system watchers directly as it is available in read-mode only. Does anyone have a fix?

**Comment by roboxv** [comment]
`.gitlab-ci.yml` which works for me.

```yaml
image: node:8

stages:
  - deploy

expo-deployments:
  stage: deploy
  only:
    - master
  before_script:
    - echo fs.inotify.max_user_instances=524288 | tee -a /etc/sysctl.conf && sysctl -p
    - echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p
    - echo fs.inotify.max_queued_events=524288 | tee -a /etc/sysctl.conf && sysctl -p
    - yarn global add expo-cli
    - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
  script:
    - yarn install
    - expo publish --non-interactive --release-channel=staging
```
