### ISSUE TITLE
Expo CLI does not generate `name` property in package.json

### ISSUE THREAD

**Issue by SebastianKurp** [expo/expo-cli#3901]
### Summary

My team was running into an issue with travis ci not building and the issue came to be that `@babel/core@7.8.3` required a `name` property in the `package.json` to build successfully. 
Our solution was to follow this [Stack Overflow's solution](https://stackoverflow.com/questions/59777226/npm-ci-throws-exception-cannot-read-property-length-of-undefined/60112825#60112825) and add a name property to the `package.json`
I believe a remedy to solve this would be to add the name field to the `package.json` when creating a new expo app from the CLI similar to Create React Apps CLI.

### Environment

Not sure this is needed...

### Please specify your device/emulator/simulator platform, model and version

Travis CI build pipeline.

### Error output

```
11424 info lifecycle @babel/core@7.8.3~postinstall: @babel/core@7.8.3

11425 info lifecycle undefined@undefined~install: undefined@undefined

11426 verbose stack TypeError: Cannot read property 'length' of undefined

11426 verbose stack at _incorrectWorkingDirectory (/home/vallo/.nvm/versions/node/v12.14.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:114:60)

11426 verbose stack at /home/vallo/.nvm/versions/node/v12.14.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:86:44

11426 verbose stack at /home/vallo/.nvm/versions/node/v12.14.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:218:12

11426 verbose stack at callback (/home/vallo/.nvm/versions/node/v12.14.0/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:295:20)

11426 verbose stack at FSReqCallback.oncomplete (fs.js:159:5)

11427 verbose cwd /home/vallo/project

11428 verbose Linux 5.3.0-26-generic

11429 verbose argv "/home/vallo/.nvm/versions/node/v12.14.0/bin/node" "/home/vallo/.nvm/versions/node/v12.14.0/bin/npm" "ci"

11430 verbose node v12.14.0

11431 verbose npm v6.13.6

11432 error Cannot read property 'length' of undefined

11433 verbose exit [ 1, true ]
```

### Reproducible demo or steps to reproduce from a blank project

Here's the `travis.yml` we're using
```
language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g npm@latest
  - npm install
  - npm install jest-expo
  - npm install -g expo-cli
script:
  - npm ci
  - npx jest --ci
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - npm ci
        - npx expo publish --non-interactive
```
