### ISSUE TITLE
Template ReactNative with NextJS 

### ISSUE THREAD

**Issue by erwanvivien** [expo/expo-cli#3910]
### Summary

When creating a new project with the nextJS template, I can't download dependencies, it says it is looking for undefined@undefined

### Environment

**Note:** I'm using WSL
```yml
  Expo CLI 4.12.1 environment info:
    System:
      OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 16.11.1 - /usr/bin/node
      npm: 8.0.0 - /usr/bin/npm
    npmPackages:
      react: ^17.0.2 => 17.0.2 
    npmGlobalPackages:
      expo-cli: 4.12.1
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

WSL Ubuntu-20.04

### Error output

```bash
test $ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"16.13.1" from react-native@0.63.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/vivien/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vivien/.npm/_logs/2021-10-13T10_58_25_074Z-debug.log
```

### Reproducible demo or steps to reproduce from a blank project

`echo test | npx create-react-native-app -t with-nextjs && cd test && npm i`
