### ISSUE TITLE
Missing dependency express

### ISSUE THREAD

**Issue by robertherber** [expo/expo-cli#3990]
### Summary

Running `expo-cli` globally or through npx causes errors when `express` is required (basically everything web-related). My current fix is to install just `express` as a devDependency. Having `expo-cli` installed as a devDependency also fixes it - I guess it resolves subdependencies differently (but I'm trying to keep my node_modules lean). I would propose to add `express` as a direct dependency to `expo-cli` to fix this.

### Environment

```yml
  Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
      Watchman: 2021.11.01.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 29, 30, 31
        Build Tools: 29.0.2, 30.0.2, 31.0.0
        System Images: android-22 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.16.2 => 0.16.7
      expo: ^43.0.0 => 43.0.2
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

web build

### Error output

```bash
$ expo build:web
Cannot find module 'express'
Require stack:
- /Users/robertherber/code/schedulist/schedulist-app/webpack.config.js
- /Users/robertherber/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/node_modules/xdl/build/Webpack.js
- /Users/robertherber/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/node_modules/xdl/build/internal.js
- /Users/robertherber/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/node_modules/xdl/build/index.js
- /Users/robertherber/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/build/exp.js
- /Users/robertherber/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/bin/expo.js
Error: Cannot find module 'express'
Require stack:
- /Users/robertherber/code/schedulist/schedulist-app/webpack.config.js
- /Users/robertherber/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/node_modules/xdl/build/Webpack.js
- /Users/robertherber/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/node_modules/xdl/build/internal.js
- /Users/robertherber/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/node_modules/xdl/build/index.js
- /Users/robertherber/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/build/exp.js
- /Users/robertherber/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/bin/expo.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/robertherber/code/schedulist/schedulist-app/webpack.config.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadConfigAsync (/Users/robertherber/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/node_modules/xdl/src/Webpack.ts:656:27)
    at Object.bundleAsync (/Users/robertherber/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/node_modules/xdl/src/Webpack.ts:455:24)
error Command failed with exit code 1.
```

### Reproducible demo or steps to reproduce from a blank project

1. expo init
2. npm install -g expo-cli
3. expo build:web
