### ISSUE TITLE
Can't do expo publish:rollback when runtimeVersion is used

### ISSUE THREAD

**Issue by jleem99** [expo/expo-cli#4286]
### Summary

`❯ expo publish:rollback --release-channel staging` gives following error
```
--release-channel and either --sdk-version or --runtime-version arguments are required.
For example, to roll back the revision [YDYHhq5P0] on release channel [default] (published 2 days ago),
run: expo publish:rollback --release-channel default --sdk-version 44.0.0
```

<br />

But when I run `❯ expo publish:rollback --release-channel staging --runtime-version 1.1.1`
```
error: unknown option `--runtime-version'
```

It does not recognize the `--runtime-version` option.

<br />

---
I can't even do `❯ expo publish:rollback --release-channel staging --sdk-version 44.0.0` when runtimeVersion is used.
```
There isn't anything published for release channel: staging, sdk version: 44.0.0, platform: android
```

### Environment

```yaml
  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v14.18.1/bin/yarn
      npm: 8.1.3 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
    npmGlobalPackages:
      eas-cli: 0.48.2
      expo-cli: 5.3.0
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

iPhon 13 (iOS 15.4)

### Error output

```error: unknown option `--runtime-version'```

### Reproducible demo or steps to reproduce from a blank project

1. Setup expo project with runtimeVersion set in app.json
2. expo publish with some updates
3. run `expo publish:rollback --release-channel [release-channel] --runtime-version [runtime-version]`
