### ISSUE TITLE
(doctor) cannot run expo-doctor in GitHub Actions

### ISSUE THREAD

**Issue by blimmer** [expo/expo-cli#4753]
### Summary

I get an error when I try to run expo-doctor via GitHub Actions:

```yml
name: Expo Doctor
on:
  push:
    paths:
      - eas.json
      - app.json
      - package.json
      - package-lock.json
      - .github/workflows/expo-doctor.yml

jobs:
  expo-doctor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
      - run: npx expo-env-info
      - name: Run expo-doctor
        run: npx expo-doctor@latest
```

[5_Run expo-doctor.txt](https://github.com/expo/expo-cli/files/12478154/5_Run.expo-doctor.txt)

### Environment

From GitHub actions:

```
Run npx expo-env-info
  npx expo-env-info
  shell: /usr/bin/bash -e {0}
  env:
    MSYS: winsymlinks:nativestrict
  
npm WARN exec The following package was not found and will be installed: expo-env-info@1.0.5

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 18.17.1 - /opt/hostedtoolcache/node/18.17.1/x64/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.6.7 - /opt/hostedtoolcache/node/18.17.1/x64/bin/npm
    SDKs:
      Android SDK:
        API Levels: 27, 28, 29, 30, 31, 32, 33, 33, 33, 34
        Build Tools: 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1, 33.0.2, 34.0.0
        Android NDK: 25.2.9519653
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

GitHub Actions with Node 18

### Error output

![Screenshot 2023-08-30 at 10 39 49](https://github.com/expo/expo-cli/assets/630449/9fe94236-d72e-4333-a468-e2d1d9d4c66a)

[logs](https://github.com/expo/expo-cli/files/12478154/5_Run.expo-doctor.txt)

### Reproducible demo or steps to reproduce from a blank project

https://github.com/blimmer/expo-createurl-bug/pull/4
https://github.com/blimmer/expo-createurl-bug/actions/runs/6027594554/job/16353121192
